config/routes.rb
Sfblog::Application.routes.draw do
  # Backoffice
  namespace :admin do
    resources :posts, except: [:show] do
      resources :post_pictures, only: [:index, :new, :create]
      post :toggle_published, :on => :member
    end
    resources :post_pictures, only: [:destroy] do
      post :sort, :on => :collection
    end
    resources :users, only: [:index, :new, :create, :destroy]

    root to: 'posts#index'
  end

  resources :posts, only: [:show]

  resources :sessions, only: [:new, :create, :destroy]
  resources :password_resets, only: [:new, :create, :edit, :update]

  # Sessions
  get 'logout' => 'sessions#destroy', as: 'logout'
  get 'login' => 'sessions#new', as: 'login'

  root to: 'posts#index'
end

app/models/post.rb
class Post < ActiveRecord::Base
  include SlugBuilder
  attr_accessible :title, :content, :cover_text, :published, :date, :secondary, :cover_picture

  has_many :post_pictures, dependent: :destroy

  mount_uploader :cover_picture, CoverPictureUploader

  build_slug column_name: :title

  validates_presence_of :title

  scope :published, where(published: true)
  scope :newest_first, order(arel_table[:date].desc)
  scope :before_now, where(arel_table[:date].lt(DateTime.now))
  scope :primary, where(secondary: false)
  scope :secondary, where(secondary: true)
end

app/controllers/admin/posts_controller.rb
# encoding: utf-8

class Admin::PostsController < Admin::ApplicationController
  before_filter :find_post, only: [:edit, :update, :destroy, :toggle_published]

  def index
    @posts = Post.newest_first
  end

  def new
    @post = Post.new
    @post.date = DateTime.now
  end

  def create
    @post = Post.new(params[:post])

    if @post.save
      # Add all post pictures without post
      PostPicture.no_post.update_all(post_id: @post.id)

      flash[:notice] = "Hola Evuxi! Has creat un post correctament. T'estimo moltíssim!"
      redirect_to admin_posts_path
    else
      flash[:alert] = "Correct the errors guapita ;)"
      render :action => :new
    end
  end

  def update
    if @post.update_attributes(params[:post])
      flash[:notice] = "Post actualitzat correctament"
      redirect_to admin_posts_path
    else
      flash[:alert] = "Correct the errors guapita ;)"
      render :action => :edit
    end
  end

  def destroy
    @post.destroy
    flash[:notice] = "Post desgraciadament eliminat, pobrissó"
    redirect_to :back
  end

  def toggle_published
    @post.toggle!(:published)

    redirect_to :back
  end

  private

  def find_post
    @post = Post.find_for_show(params[:id])
  end
end

app/controllers/posts_controller.rb
# encoding: utf-8

class PostsController < ApplicationController
  def index
    @posts = Post.published.primary.before_now.newest_first
    @secondary_posts = Post.published.secondary.before_now.newest_first
  end

  def show
    @post = Post.find_for_show(params[:id])
  end
end

app/views/admin/posts/_edit_header.html.slim
= link_to admin_posts_path, class: 'btn' do
  i class="icon-arrow-left"
  |  Back

.posts-edit-menu.tabs-edit-menu
  h1.pull-left
    ' posts
    small
      ' Editing
      = @post.title
  ul.nav.nav-pills.pull-left
    li class=(controller_name == 'posts' ? 'active' : '' )
      = link_to "Info", edit_admin_post_path(@post)
    li class=(controller_name == 'post_pictures' ? 'active' : '' )
      = link_to "Pictures", admin_post_post_pictures_path(@post)
  .info.pull-right
    = yield :actions

app/views/admin/posts/_form.html.slim
= simple_form_for [:admin, @post], html: { class: "form-horizontal", 'data-slug' => @post.slug, id: 'post_form' }, defaults: { wrapper: :with_controls, label_html: { class: 'form--horizontal__control-label' } } do |f|

  = f.input :secondary, label: 'Secundari'
  = f.input :title, label: "Títol", input_html: { class: 'input-xxlarge' }
  = f.input :cover_picture, :label => "Imatge de la capçalera"
  = f.input :cover_text, label: "Descripció curta", as: :text, input_html: { class: 'redactor' }
  = f.input "content", label: "Content", as: :text, input_html: { class: 'redactor_pictures' }

  = f.input :date, :label => 'Data', :as => :datetime_picker

  .controls
    = f.button :submit, "Guardar", class: 'btn-success'

app/views/admin/posts/_header.html.slim
#member-header
  = yield :actions

  h1.page-header 
    =' title
    - if defined? subtitle
      small= subtitle

app/views/admin/posts/edit.html.slim
= render 'edit_header', title: 'Editing post', subtitle: @post.title

= render 'form'

app/views/admin/posts/index.html.slim
- content_for :actions do
  = link_to 'New Post', new_admin_post_path, class: "btn btn-success pull-right"

= render 'header', title: 'Posts'

.posts-list
  - if @posts.any?
    table.table.table-striped
      thead
        tr
          th
          th
          th Title
          th Content
          th Date
          th
          th

      thbody
        - @posts.each do |post|
          tr.item
            td
              - with_publication(post) do |copy, klass|
                = link_to copy, toggle_published_admin_post_path(post), :method => :post, class: "btn btn-mini #{klass}"
            td(style='width:120px;')= image_tag post.cover_picture.mini unless post.cover_picture.blank?
            td= post.title
            td= post.cover_text
            td= post.date.strftime("%d/%m/%Y %H:%M")
            td= 'Secundari' if post.secondary?
            td
              = link_to 'Delete', admin_post_path(post), :confirm => "Are you sure?", :method => :delete, :class => "btn btn-danger btn-small pull-right"

              = link_to t('edit', scope: 'actions'), edit_admin_post_path(post), class: "btn btn-warning btn-small pull-right"
  - else
    #none.well There are no posts

app/views/admin/posts/new.html.slim
= link_to admin_posts_path, class: 'btn' do
  i class="icon-arrow-left"
  |  Back

= render 'header', title: 'New post'

= render 'form'